name: digisalad_code_test_vicksonng
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  build_runner: ^2.4.6
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.4
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get: ^4.6.6
  get_it: ^7.6.4
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.2
  json_annotation: ^4.8.1

  just_audio: ^0.9.36
  logger: ^2.0.2+1
  retrofit: ^4.0.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
